### ISSUE TITLE
[Update: Fixed!] Just stopped working entirely

### ISSUE THREAD

**Issue by FlawlessWaffles** [TheRealJoelmatic/RemoveAdblockThing#306]
**Script version**
3.2

**Describe the bug**
It's not blocking any ads anymore as of the last couple days

**Expected behavior**
It worked fine for a long time, blocking video ads and ads on my homepage

**Screenshots**
![Adblock 1](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/156550109/4ac60179-8538-4c25-8796-b871c671fdb5)
![Adblock 2](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/156550109/9b5da2cd-542f-4b7c-8f89-146e32aadd4e)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX
 - Version: Windows 10

**Additional context**
Like I said before, the adblock thing has been working great for a couple months now but just suddenly stopped working. I've checked to make sure my browser is updated properly, the adblock is updated properly, and I've tried rebooting my computer several times. I really love this extension and can't find another one like it, I really want to fix it! Thank you for whatever help you can offer!

**Comment by TheRealJoelmatic** [comment]
Check out 3.3, This should now be fixed.

**Comment by Solvmane** [comment]
same issue, went and verified the updated version was downloaded too. still getting ads
