### ISSUE TITLE
youtube says "ad blocking is not permitted" and not able to play videos

### ISSUE THREAD

**Issue by lorduak** [TheRealJoelmatic/RemoveAdblockThing#407]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by PhoenixRx7** [comment]
Same deal.
Windows 10
Chrome 125.0.6422.77
Version 4.0

**Comment by bazmn** [comment]
Likewise.
Mac iOS Monterey 12.6
Chrome 124.0.6367.119
Version 4.0

**Comment by yafet188** [comment]
Same here.
Windows 11 
Brave Browser 125.0.6422.112
Version 1.66.115

**Comment by ralinchan** [comment]
Currently not seeing this issue on script v4.0 with Firefox

**Comment by FrostbearDeluxe** [comment]
same
Windows 10
Opera GX Browser 109.0.5097.108
chromium version: 123.0.6312.124

Version 4.0

**Comment by PlayerNguyen** [comment]
The same here 

Windows 11
Edge: Version 125.0.2535.67 (Official build) (64-bit)
Version: 4.0

**Comment by gh0st11111** [comment]
Also, same.

Windows 10
Brave 1.66.115
Version 4.0

**Comment by RyotoK** [comment]
Same here too.
Windows 10
Edge Version 125.0.2535.67 
Version 4.0

**Comment by WyattSL** [comment]
Same here too.
Windows 10
Firefox V 126.0.1 (64-bit)
Version 4.0

First Firefox report?

**Comment by yukkeyukka02** [comment]
Same here too.

windows10
chrome ver. 125.0.6422.78 (64 bit)

**Comment by SamBWarren** [comment]
Same here, version 2.9 which always worked previously.

Windows 11
Firefox 126.0.1 64-bit

**Comment by ralinchan** [comment]
> Same here too. Windows 10 Firefox V 126.0.1 (64-bit) Version 4.0
> 
> First Firefox report?

Not seeing this
FF 126.0.1
Script v4.0

**Comment by yoghurtbal** [comment]
Same here, version 2.9 which always worked previously.

Windows 11

Same here too.

windows10
chrome ver. 125.0.6422.78 (64 bit)

**Comment by ralinchan** [comment]
> W10 FF 126.0.1 Script v4.0

This is what I am running and I am not encountering any issues. What addons do you have running besides the script?

**Comment by Effectz-End** [comment]
Same Issue
Firefox 126.0 
Ubuntu, 22.04
Tested on version 2.9 and 4.0

**Comment by ralinchan** [comment]
> Same Issue Firefox 126.0 Ubuntu, 22.04 Tested on version 2.9 and 4.0

Check your own addons for conflicts.

Win 10
Script v4.0

No issue on FF 126.0.1

Also for people using Brave, i'm seeing no issue with just Brave's built in adblocker on Chromium v 125.0.6422.112

**Comment by PhoenixRx7** [comment]
Fresh install of FF and TM 126.0.1 (64-bit)
Win 10, no other addons... works fine :-/

Turned off "return YT dislike button"
Turned off "SponsorBlock"
Removed adblock all together.

Still broken on Chrome.

Removed completely all of the above extensions. Still broken on Chrome.
Looking into Chrome's native adblocking? If that is a thing?

**Comment by pedrofsantoscom** [comment]
1. disabled `RemoveAdBlockThing` on tampermonkey
2. enabled uBlock Origin blocking on YT
3. chrome v125.0.6422.113 works for me now

**Comment by TheRealJoelmatic** [comment]
I've updated the script to fix the detection. Please let me know if it works for u now. v5.0

**Comment by ZDawgKiller** [comment]
Im Still Getting The Issue on 
Opera Gx When Running The New Code 
It Still Detects It

**Comment by KasselMarc** [comment]
> I've updated the script to fix the detection. Please let me know if it works for u now. (v5.0)

It still doesn't work on Chrome (latest).

**Comment by slzero-X** [comment]
@KasselMarc and @ZDawgKiller 

Check any of these things as seen on the Readme

Adblock extension: Disable or whitelist YouTube on your ad blocker extension.

Browser built-in adblock: Some browsers have built-in ad blockers. Disable or configure them.

Other Tampermonkey scripts: Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

Wi-Fi/DNS/Firewall adblock rules: Check network settings for any ad-blocking configurations.

Windows hosts file rules: Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.

**Comment by ZDawgKiller** [comment]
i have disabled all ad blocker extensions don't have any other scrips for tamper monkey ,and no wi-fi/dns/firewall rules 
nore windows host files for ad blocking rules , nore any built in AdBlock as i disabled them and it still now working

**Comment by slzero-X** [comment]
YEP THEY CRAKED DOWN ON THIS TOO

**Comment by Lewis-Gith** [comment]
The Same。。。
Version is 5.0 now。。。
But happens again。

**Comment by pedrofsantoscom** [comment]
> I've updated the script to fix the detection. Please let me know if it works for u now. (v5.0)

Works for me. 
Latest chrome v125.0.6422.142 on mac. No extra tampermonkey scripts enabled. No adblocker extensions enabled for YT. Also did `Empty cache and hard reload` and still works.

**Comment by Scott16546** [comment]
it's fine for me too

**Comment by Scott16546** [comment]
![Screenshot 2024-05-31 at 07 09 10](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/82477557/31f2267a-ae26-406f-9980-12cf42a87dd6)

**Comment by NicePaddy** [comment]
Same Issue
Windows 7
Chrome, version 109.0.5414.120 (64 bit)
Version 5.0

**Comment by slzero-X** [comment]
Its been cracked down on, I even had it enabled completely by itself, and the "violate terms of service" popped up immediately when going towards another video less than an hour later. @TheRealJoelmatic 

All 5 things checked out, they finally implemented algorithmic detection, so now any form of blocking from ANY source will trigger it.

You have to buy premium now, we lost the war.

**Comment by hacs64** [comment]
> ![Screenshot 2024-05-31 at 07 09 10](https://private-user-images.githubusercontent.com/82477557/335610357-31f2267a-ae26-406f-9980-12cf42a87dd6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjcwNjUsIm5iZiI6MTcxNzE2Njc2NSwicGF0aCI6Ii84MjQ3NzU1Ny8zMzU2MTAzNTctMzFmMjI2N2EtYWUyNi00MDZmLTk5ODAtMTJjZjQyYTg3ZGQ2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE0NDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZDAwYWQ1ZDVkODRmZmFhNTZjYmZiOTgzMjlmMTBmZDE3OTk0N2NiMjhjODlkMmFhYzUzOTc1YWQ0MGNkOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rb8S-Sig7z4oVYAFJ27aN46wSfLCPzCKobuVEp8m0kA)

Could you share links to all of your scripts?

**Comment by Franciscoelabreu** [comment]
RIP my G

**Comment by PhoenixRx7** [comment]
Still having issues with chrome. Checked the other places (other scripts, firewall rules etc) and Chrome still gets the notification.

Version 5 does not seem to make a difference.
I have noticed that adverts within videos are blocked/skipped, not sure if that is a relevant data point.

**Comment by Smith873** [comment]
The v5 update is working for me.

Win 7, Firefox 115,11,0esr

**Comment by PhoenixRx7** [comment]
I am having suspicions that Chrome, being owned by google, may* be "leaking" info about blockers. If it works in FF, but not in Chrome, that seems odd.
It could also mean the google is much better acquainted with the inner workings of chrome and can do "non-dodgy" tests for this particular kind of scipt.

**Comment by Effectz-End** [comment]
Just checked the 5.0 version, doesn't work for me

**Comment by Enzocarva** [comment]
Version 5.0 also not working for me using Userscripts on mac, used to work perfectly with the following specs until today
OS: macOS (Sonoma 14.4)
Browser: Safari

**Comment by slzero-X** [comment]
I am sorry to tell you this, but...Joel, YouTube has defeated you.

Everyone is going here to complain constantly, and based on the rate at which it's coming in, you've been defeated.

You're going to have to stop developing this or YouTube's gonna send a cease and desist.

**Comment by ralinchan** [comment]
> I am sorry to tell you this, but...Joel, YouTube has defeated you.
> 
> Everyone is going here to complain constantly, and based on the rate at which it's coming in, you've been defeated.
> 
> You're going to have to stop developing this or YouTube's gonna send a cease and desist.

lol. Bunch of user errors being attributed to the developer releasing software for free.

**Comment by Wiese2007** [comment]
> W10 FF 126.0.1 Script v4.0

with v5.0 it works fine now

**Comment by surz-p** [comment]
> I've updated the script to fix the detection. Please let me know if it works for u now. (v5.0)

It's 50-50 for me. Sometimes the video plays too smoothly, as if there never existed an ad. (Previously the add would pop up for a few milliseconds on the screen and then would get skipped)
Sometimes, YT shows the adblock warning screen.

schrodinger's ads.

**Comment by Enzocarva** [comment]
@Wiese2007 What are you using that is working (OS, browser, etc)?

**Comment by Wiese2007** [comment]
@Enzocarva if you look again you see i have replyed at my own post with the settings xD

**Comment by supersmith2500** [comment]
> I am sorry to tell you this, but...Joel, YouTube has defeated you.
> 
> Everyone is going here to complain constantly, and based on the rate at which it's coming in, you've been defeated.
> 
> You're going to have to stop developing this or YouTube's gonna send a cease and desist.

Stop admiting defeat! There will be ways round.

**Comment by TheRealJoelmatic** [comment]
> I am sorry to tell you this, but...Joel, YouTube has defeated you.
> 
> Everyone is going here to complain constantly, and based on the rate at which it's coming in, you've been defeated.
> 
> You're going to have to stop developing this or YouTube's gonna send a cease and desist.

First of all I will never admit defeat as I use youtube on the daily and refuse to watch any kind of ads at all.

Pushed new version 5.1. Let me know if it works.

**Comment by slzero-X** [comment]
Still gets detected @TheRealJoelmatic

**Comment by VerzatileDev** [comment]
> ![Screenshot 2024-05-31 at 07 09 10](https://private-user-images.githubusercontent.com/82477557/335610357-31f2267a-ae26-406f-9980-12cf42a87dd6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODgzODIsIm5iZiI6MTcxNzE4ODA4MiwicGF0aCI6Ii84MjQ3NzU1Ny8zMzU2MTAzNTctMzFmMjI2N2EtYWUyNi00MDZmLTk5ODAtMTJjZjQyYTg3ZGQ2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDIwNDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkYjllZmJkY2E3M2JiODI5ZTc4OTMzNTA3OGM4ZWYwYjFjNWRlYzAzOTU2YzY1ZmZmZWM2NjY0MjZjZGQ5ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9mR1n_ya_S8EJawQLic0ZQx7ONUFEXBDKE3erLwancw)

Damn  you are dedicated my dude.

Other than that it seems Youtube pushed another update to avoid the latest update

**Comment by slzero-X** [comment]
@Scott16546 I tried that shit
Still got the fucking POPUP!

**Comment by ralinchan** [comment]
> Pushed new version 5.1. Let me know if it works.

For Firefox, 5.1 seems worse than 5.0.

The fast forwarding of ads in 5.0 was instant as it usually was. 5.1 now makes it seem like it's maybe double/triple speed so instead of completely bypassing the ad, you're watching 10-20 seconds of it in fast forward

**Comment by PhoenixRx7** [comment]
> > I am sorry to tell you this, but...Joel, YouTube has defeated you.
> > Everyone is going here to complain constantly, and based on the rate at which it's coming in, you've been defeated.
> > You're going to have to stop developing this or YouTube's gonna send a cease and desist.
> 
> lol. Bunch of user errors being attributed to the developer releasing software for free.
> 
> Works completely without issue on FF

This comment is as unhelpful as the one it commented on.
(Kinda like this one I guess??)

5.1 works for me on chrome.... kinda.

I don't get the adverts sometimes, other times I get them at fast forward. I have yet to get the warning screen, so that is progress.

**Comment by gh0st11111** [comment]
I just updated to 5.1, and it's giving me the same error. It's blocking videos from playing. However, the Brave Shields adblock has been working fine but I have a feeling that won't last very long.

I am running:
Brave 1.66.115, chromium version 125.0.6422.112 64-bit

**Comment by lorduak** [comment]
After updating to 5.1, no error shows and ads are skipped beautifully. Should I close the Issue?

**Comment by lorduak** [comment]
After updating to 5.1, after skipping 2-3 videos, error is still persistent!

**Comment by FrozenDragon0** [comment]
Still having the same problem on 5.1, YouTube is really damn determined to crack down on this script.

**Comment by Wiese2007** [comment]
> @Enzocarva if you look again you see i have replyed at my own post with the settings xD W10 FF 126.0.1 Script v5.0

W10 FF 126.0.1 Script v5.2 and now it shows them again - mostly after 3 websitereloads it works

**Comment by Meg923a** [comment]
v5.1 is working fine for me
Windows 10
Chrome 125.0.6422.113 (64 bit)
Script v5.1

**Comment by FrozenDragon0** [comment]
5.2 Still having issues, and now I've noticed the ads during videos aren't skipped and are instead played super fast.

**Comment by PhoenixRx7** [comment]
5.2 works perfectly for me.

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
